"""empty message

Revision ID: 18211ed9ff1b
Revises: 
Create Date: 2022-07-21 18:30:20.115470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18211ed9ff1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
