"""empty message

Revision ID: 38dd4e877dc7
Revises: d2fe62fdea4e
Create Date: 2022-07-21 20:06:33.850172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38dd4e877dc7'
down_revision = 'd2fe62fdea4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('hour', sa.Time(), nullable=True),
    sa.Column('temperature', sa.String(length=50), nullable=True),
    sa.Column('pressure', sa.String(length=50), nullable=True),
    sa.Column('humidity', sa.String(length=50), nullable=True),
    sa.Column('pm_2_5', sa.String(length=50), nullable=True),
    sa.Column('pm_10', sa.String(length=50), nullable=True),
    sa.Column('wind', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_created_at'), 'measurements', ['created_at'], unique=False)
    op.create_index(op.f('ix_measurements_hour'), 'measurements', ['hour'], unique=False)
    op.create_index(op.f('ix_measurements_humidity'), 'measurements', ['humidity'], unique=False)
    op.create_index(op.f('ix_measurements_id'), 'measurements', ['id'], unique=False)
    op.create_index(op.f('ix_measurements_pm_10'), 'measurements', ['pm_10'], unique=False)
    op.create_index(op.f('ix_measurements_pm_2_5'), 'measurements', ['pm_2_5'], unique=False)
    op.create_index(op.f('ix_measurements_pressure'), 'measurements', ['pressure'], unique=False)
    op.create_index(op.f('ix_measurements_temperature'), 'measurements', ['temperature'], unique=False)
    op.create_index(op.f('ix_measurements_wind'), 'measurements', ['wind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_wind'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_temperature'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_pressure'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_pm_2_5'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_pm_10'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_humidity'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_hour'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_created_at'), table_name='measurements')
    op.drop_table('measurements')
    # ### end Alembic commands ###
