"""empty message

Revision ID: d2fe62fdea4e
Revises: 18211ed9ff1b
Create Date: 2022-07-21 20:04:23.427620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2fe62fdea4e'
down_revision = '18211ed9ff1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
